# Generated by Django 4.2.1 on 2023-05-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDog',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('raca', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_alimentacao', models.CharField(max_length=100)),
                ('restricoes_alimentares', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_tutor', models.CharField(blank=True, max_length=100)),
                ('contato_tutor', models.CharField(max_length=100)),
                ('cpf_tutor', models.PositiveIntegerField()),
                ('endereco', models.TextField(max_length=100)),
                ('veterinario_cao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Ficha_Dog',
            },
        ),
    ]
