# Generated by Django 4.2.2 on 2023-06-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaDog',
            fields=[
                ('nome', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('raca', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_alimentacao', models.CharField(max_length=100)),
                ('restricoes_alimentares', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_tutor', models.CharField(blank=True, max_length=100)),
                ('contato_tutor', models.CharField(max_length=100)),
                ('cpf_tutor', models.CharField(max_length=14)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Ficha_Dog',
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('validade', models.DateField()),
                ('data_reforco', models.DateField()),
            ],
            options={
                'db_table': 'Vacina',
            },
        ),
        migrations.CreateModel(
            name='VacinaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_administracao', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.vacina')),
            ],
            options={
                'db_table': 'Vacina_Animal',
            },
        ),
    ]
