# Generated by Django 4.2.1 on 2023-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadog',
            name='cpf_tutor',
            field=models.CharField(max_length=14),
        ),
    ]
