# Generated by Django 4.2 on 2023-05-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichadog',
            old_name='veterinario_cao',
            new_name='veterinario',
        ),
        migrations.AddField(
            model_name='fichadog',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichadog',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
