# Generated by Django 4.2 on 2023-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_fichadog_data_de_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadog',
            name='idade',
        ),
        migrations.AlterField(
            model_name='fichadog',
            name='data_de_nascimento',
            field=models.DateField(),
        ),
    ]
