# Generated by Django 4.2 on 2023-05-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0005_remove_fichadog_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadog',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
