# Generated by Django 4.2 on 2023-05-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0006_alter_fichadog_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadog',
            name='cpf_tutor',
            field=models.CharField(max_length=100),
        ),
    ]
