# Generated by Django 4.2.2 on 2023-06-20 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaBanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banhista', models.CharField(max_length=100)),
                ('relatorio_estadia', models.TextField(max_length=500)),
                ('desconto', models.DecimalField(decimal_places=1, max_digits=3)),
                ('metodo_de_pagamento', models.CharField(choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Debito', 'Cartão de Debito'), ('Dinheiro', 'Dinheiro'), ('Pix', 'Pix')], max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'CaixaBanho',
            },
        ),
    ]
