# Generated by Django 4.2 on 2023-05-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_pacote_reservaday_pacote'),
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaday',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.pacote'),
        ),
    ]
