# Generated by Django 4.2.2 on 2023-06-20 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
        ('hotel', '0002_reservabanho'),
        ('caixa', '0002_caixabanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixabanho',
            name='num_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.reservabanho'),
        ),
        migrations.AddField(
            model_name='caixabanho',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog'),
        ),
    ]
