# Generated by Django 4.2.2 on 2023-06-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_caixabanho_num_reserva_caixabanho_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caixabanho',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='caixaday',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
