# Generated by Django 4.2.2 on 2023-06-20 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaBanho',
            fields=[
                ('num_reserva', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('data_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('status_de_pagamento', models.BooleanField(choices=[(False, 'Não Pago'), (True, 'Pago')], default=False, null=True)),
                ('observacoes', models.TextField(max_length=100)),
                ('banhista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cachorro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha.fichadog')),
                ('tipo_banho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.servicosadicionais')),
            ],
        ),
    ]
