# Generated by Django 4.2 on 2023-05-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_pacote_reservaday_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaday',
            name='dias_utilizados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
